# Generated by Django 4.1.2 on 2022-11-02 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=800, verbose_name='texto')),
            ],
            options={
                'db_table': 'app_story_page',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
            ],
            options={
                'db_table': 'app_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='username')),
                ('password', models.CharField(max_length=150, verbose_name='password')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('cover', models.ImageField(default='imagenes/portadas/book-default.png', upload_to='imagenes/portadas/', verbose_name='cover')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='description')),
                ('route', models.SlugField(default='', max_length=255, unique=True)),
                ('tag', models.ManyToManyField(blank=True, to='main.tag')),
            ],
            options={
                'db_table': 'app_story',
            },
        ),
        migrations.CreateModel(
            name='RepeatPhrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('translation', models.CharField(max_length=255, verbose_name='translation')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.page')),
            ],
            options={
                'db_table': 'app_page_repeat_phrase',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.page')),
            ],
            options={
                'db_table': 'app_page_question',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.story'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255, verbose_name='answer')),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'db_table': 'app_page_question_option',
            },
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('translation', models.CharField(max_length=255, verbose_name='translation')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.page')),
            ],
            options={
                'db_table': 'app_page_dialogue',
            },
        ),
    ]
