# Generated by Django 4.1.2 on 2023-01-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='comprehension_percentage',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='scores',
            name='speaking_percentage',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='scores',
            name='writing_percentage',
            field=models.FloatField(default=100),
        ),
    ]
