# Generated by Django 4.1.2 on 2023-02-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_stories',
            field=models.ManyToManyField(related_name='users_liked', to='main.story'),
        ),
    ]
