# Generated by Django 4.1.2 on 2023-01-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
            options={
                'db_table': 'completed_story',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='completed_stories',
            field=models.ManyToManyField(related_name='completed_by', through='main.CompletedStory', to='main.story'),
        ),
    ]
