# Generated by Django 4.1.2 on 2022-11-14 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(default=0, verbose_name='page_type'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='imagenes/img-pages/', verbose_name='image')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.page')),
            ],
            options={
                'db_table': 'main_page_image',
            },
        ),
    ]
