# Generated by Django 4.1.2 on 2022-11-20 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_page_page_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogue',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='element_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='element_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='element_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repeatphrase',
            name='element_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page'),
        ),
        migrations.AlterField(
            model_name='dialogue',
            name='translation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='imagenes/img-pages/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page'),
        ),
        migrations.AlterField(
            model_name='repeatphrase',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page'),
        ),
        migrations.CreateModel(
            name='VideoUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=2048)),
                ('element_number', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.page')),
            ],
            options={
                'db_table': 'main_page_video_url',
            },
        ),
    ]
