# Generated by Django 4.1 on 2022-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, verbose_name='titulo')),
                ('portada', models.ImageField(upload_to='imagenes/portadas/', verbose_name='portada')),
                ('descripcion', models.CharField(max_length=100, verbose_name='descripcion')),
            ],
        ),
        migrations.RenameModel(
            old_name='Categorias',
            new_name='Categoria',
        ),
    ]
