# Generated by Django 4.1.2 on 2023-02-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_story_likes_number_userprofile_liked_stories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='liked_stories',
            field=models.ManyToManyField(blank=True, related_name='users_liked', to='main.story'),
        ),
    ]
