# Generated by Django 4.1.2 on 2023-02-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_story_updated_at_story_xp_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
