# Generated by Django 4.1.2 on 2023-01-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_completedstory_userprofile_completed_stories'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='completedstory',
            table=None,
        ),
    ]
