# Generated by Django 4.1.2 on 2023-02-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatphrase',
            name='show_text',
            field=models.BooleanField(default=False),
        ),
    ]
