# Generated by Django 4.1.2 on 2023-01-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_completedstory_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completedstory',
            old_name='points',
            new_name='score',
        ),
    ]
