# Generated by Django 4.1.2 on 2023-02-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_liked_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.story')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile')),
            ],
            options={
                'db_table': 'saved_story',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_stories',
            field=models.ManyToManyField(related_name='saved_by', through='main.SavedStory', to='main.story'),
        ),
    ]
