# Generated by Django 4.1 on 2022-10-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_historia_rename_categorias_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeHistoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_historia', models.IntegerField(max_length=100, verbose_name='id_historia')),
                ('id_categoria', models.IntegerField(max_length=100, verbose_name='id_categoria')),
            ],
        ),
    ]
