# Generated by Django 4.1.2 on 2022-11-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_page_subtitle_alter_dialogue_page_alter_image_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='time_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
