# Generated by Django 4.1 on 2022-10-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categoriadehistoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriadehistoria',
            name='id_categoria',
            field=models.IntegerField(verbose_name='id_categoria'),
        ),
        migrations.AlterField(
            model_name='categoriadehistoria',
            name='id_historia',
            field=models.IntegerField(verbose_name='id_historia'),
        ),
    ]
