# Generated by Django 4.1.2 on 2023-02-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_repeatphrase_show_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeatphrase',
            name='show_text',
            field=models.BooleanField(default=True),
        ),
    ]
