# Generated by Django 4.1.2 on 2023-02-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_savedstory_userprofile_saved_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
