# Generated by Django 4.1.2 on 2023-02-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_repeatphrase_show_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='tag',
            new_name='tags',
        ),
    ]
