# Generated by Django 4.1 on 2022-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_categoriadehistoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='descripcion',
            field=models.CharField(max_length=100, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='portada',
            field=models.ImageField(null=True, upload_to='imagenes/portadas/', verbose_name='portada'),
        ),
    ]
