# Generated by Django 4.1 on 2022-10-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_historia_descripcion_alter_historia_portada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaDeHistoria',
        ),
        migrations.AddField(
            model_name='historia',
            name='id_categoria',
            field=models.ManyToManyField(to='main.categoria'),
        ),
    ]
