# Generated by Django 4.1.2 on 2023-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_tag_story_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description1',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='description2',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='story',
            name='title2',
            field=models.CharField(max_length=255),
        ),
    ]
