# Generated by Django 4.1.2 on 2023-03-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_story_description1_alter_story_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.FloatField(default=1),
        ),
    ]
