# Generated by Django 4.1 on 2022-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_historia_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='portada',
            field=models.ImageField(default='imagenes/portadas/book.png', upload_to='imagenes/portadas/', verbose_name='portada'),
        ),
    ]
