# Generated by Django 4.1 on 2022-10-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_historia_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='id_categoria',
            field=models.ManyToManyField(blank=True, to='main.categoria'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='portada',
            field=models.ImageField(default='imagenes/portadas/book-default.png', upload_to='imagenes/portadas/', verbose_name='portada'),
        ),
    ]
