# Generated by Django 4.1 on 2022-10-14 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pagina'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='pagina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pagina'),
        ),
    ]
