# Generated by Django 4.1.2 on 2023-03-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_useranswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='object_id',
            new_name='exercise_id',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='content_type',
            new_name='exercise_type',
        ),
    ]
