# Generated by Django 4.1.2 on 2023-03-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_object_id_useranswer_exercise_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
