# Generated by Django 4.1 on 2022-10-14 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_historia_pagina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='pagina',
        ),
        migrations.AddField(
            model_name='pagina',
            name='historia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.historia'),
        ),
    ]
