# Generated by Django 4.1.2 on 2022-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_historia_pagina_pagina_historia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='texto',
            field=models.CharField(max_length=800, verbose_name='texto'),
        ),
    ]
