# Generated by Django 4.1.2 on 2022-10-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_pagina_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historia',
            name='ruta',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=100, verbose_name='ruta'),
        ),
    ]
