# Generated by Django 4.1.2 on 2023-04-10 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_text_text_text_language1_text_language2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spellcheck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('right_text', models.CharField(max_length=600)),
                ('right_text_translated', models.CharField(max_length=600)),
                ('wrong_text', models.CharField(max_length=600)),
                ('element_number', models.IntegerField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spellchecks', to='main.page')),
            ],
            options={
                'db_table': 'spellcheck',
            },
        ),
    ]
