# Generated by Django 4.1.2 on 2023-04-10 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_spellcheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spellcheck',
            old_name='right_text_translated',
            new_name='translated_right_text',
        ),
    ]
