# Generated by Django 4.1.2 on 2022-10-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_historia_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
