# Generated by Django 4.1.2 on 2022-10-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_pagina_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='app_categoria',
        ),
        migrations.AlterModelTable(
            name='historia',
            table='app_historia',
        ),
        migrations.AlterModelTable(
            name='pagina',
            table='app_historia_pagina',
        ),
        migrations.CreateModel(
            name='RepeatPhrase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('translation', models.CharField(max_length=255, verbose_name='translation')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pagina')),
            ],
            options={
                'db_table': 'app_pag_repeat_phrase',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pagina')),
            ],
            options={
                'db_table': 'app_pag_question',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255, verbose_name='answer')),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.question')),
            ],
            options={
                'db_table': 'app_pag_question_option',
            },
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('content', models.CharField(max_length=255, verbose_name='content')),
                ('translation', models.CharField(max_length=255, verbose_name='translation')),
                ('page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pagina')),
            ],
            options={
                'db_table': 'app_pag_conversation',
            },
        ),
    ]
