# Generated by Django 4.1.2 on 2023-04-26 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_right_text_translated_spellcheck_translated_right_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(default='#cbe5ff', max_length=7)),
                ('content1', models.CharField(max_length=255)),
                ('content2', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'flashcard',
            },
        ),
        migrations.CreateModel(
            name='FlashcardCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('collection_name', models.CharField(default='New Collection', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_collections', to='main.userprofile')),
            ],
            options={
                'db_table': 'flashcard_collection',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='page',
        ),
        migrations.AlterModelTable(
            name='useranswer',
            table='user_answer',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='flashcard_collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='main.flashcardcollection'),
        ),
    ]
