# Generated by Django 4.1.2 on 2022-10-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_categoria_table_alter_historia_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historia',
            name='ruta',
        ),
        migrations.AddField(
            model_name='historia',
            name='route',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
