# Generated by Django 4.1.2 on 2023-04-26 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_flashcard_flashcardcollection_remove_question_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardcollection',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards_collections', to='main.userprofile'),
        ),
    ]
