# Generated by Django 4.1.2 on 2023-05-30 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rename_content1_flashcard_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardcollection',
            name='color',
            field=models.CharField(default='#cbe5ff', max_length=7),
        ),
    ]
