# Generated by Django 4.1.2 on 2023-06-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBRSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeout', models.IntegerField(default=0)),
                ('update_on_alter_stories', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cbr_settings',
            },
        ),
        migrations.CreateModel(
            name='UBRSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timeout', models.IntegerField(default=1800)),
            ],
            options={
                'db_table': 'ubr_settings',
            },
        ),
    ]
