# Generated by Django 4.1.2 on 2023-06-01 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_cbrsettings_ubrsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSettings',
        ),
    ]
