# Generated by Django 4.1.2 on 2023-06-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_delete_appsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_number', models.IntegerField()),
                ('url', models.CharField(max_length=2048)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.page')),
            ],
            options={
                'db_table': 'video',
            },
        ),
        migrations.DeleteModel(
            name='VideoUrl',
        ),
    ]
