# Generated by Django 4.1.2 on 2023-06-08 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_question_questionoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('element_number', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('t_text', models.CharField(max_length=255)),
                ('randomize_options', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.page')),
            ],
            options={
                'db_table': 'multiple_choice_question',
            },
        ),
        migrations.CreateModel(
            name='QuestionChoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option_number', models.IntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('t_text', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main.multiplechoicequestion')),
            ],
            options={
                'db_table': 'question_choice',
            },
        ),
        migrations.RemoveField(
            model_name='questionoption',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
