# Generated by Django 4.1.2 on 2023-06-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_multiplechoicequestion_questionchoice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multiplechoicequestion',
            old_name='randomize_options',
            new_name='randomize_choices',
        ),
        migrations.RenameField(
            model_name='questionchoice',
            old_name='option_number',
            new_name='choice_number',
        ),
    ]
