# Generated by Django 4.1.2 on 2023-06-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename_randomize_options_multiplechoicequestion_randomize_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover',
            field=models.ImageField(default='main/static/img/default-cover.png', upload_to='uploads/images/', verbose_name='cover'),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_number', models.IntegerField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='uploads/audios/%Y/%m/%d/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='main.page')),
            ],
            options={
                'db_table': 'audio',
            },
        ),
    ]
