# Generated by Django 4.1.2 on 2023-08-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_storyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
